name: Deploy le book de PH
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Deploy the book to  GitHub Pages
      run: |
        # This assumes your book is in the root of your repository.
        # Just add a `cd` here if you need to change to another directory.
        git config user.name "Deploy ph book from CI"
        git config user.email ""
        git worktree add ./tmp/book gh-pages
        mdbook build
        rm -rf ./tmp/book/* # this won't delete the .git directory
        cp -rp book/* ./tmp/book/
        cd ./tmp/book
        git add -A
        git commit -m 'deploy new book'
        git push origin gh-pages
